update workflow

diff --git a/.github/workflows/packaging.yml b/.github/workflows/packaging.yml
--- a/.github/workflows/packaging.yml
+++ b/.github/workflows/packaging.yml
@@ -29,15 +29,13 @@ jobs:
       - name: Determine target name and version (ref)
         id: version
         run: |
-          LOCAL_TAGS=$(git tag)
-          UPSTREAM_TAGS=$(gh api --paginate --token "${{ secrets.GITHUB_TOKEN }}" "/repos/owncloud/web-extensions/releases" | \
-              jq -r "[.[] | select(.prerelease == false)] | sort_by(.published_at) | .[].tag_name")
-          ref=$(for tag in ${UPSTREAM_TAGS}; do if ! echo "${LOCAL_TAGS}" | grep -q "^$tag^"; then echo "${tag}"; break; fi; done)
+          ref=$(for tag in $(gh api --paginate --token "${{ secrets.GITHUB_TOKEN }}" "/repos/owncloud/web-extensions/releases" | \
+              jq -r "[.[] | select(.prerelease == false)] | sort_by(.published_at) | .[].tag_name"); do if ! git tag | grep -q "^$tag^"; then echo "${tag}"; break; fi; done)
           if [ -z "${ref}" ]; then
             echo "No missing versions found. Nothing to do."
             exit 0
           fi
-          echo "Auto-selected missing version: $REF"
+          echo "Auto-selected missing version: ${ref}"
           echo "ref=${ref}" >> $GITHUB_OUTPUT
           echo "pkg=${ref}" | sed "s/-v.*//" >> $GITHUB_OUTPUT
           echo "ver=${ref}" | sed "s/=.*-v/=/" >> $GITHUB_OUTPUT
